AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Nested Stack for IAM SA.

Parameters:
  BucketCfn:
    Type: String
    Description: El nombre del bucket de S3 para los templates de CloudFormation

  BucketName:
    Type: String
    Description: Nombre del bucket de S3

Resources:
  RolesCorentsu:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${BucketCfn}.s3.${AWS::Region}.amazonaws.com/icloud/cfn-nested/corentsu/roles-corentsu.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName

  PoliciesCiclos:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://${BucketCfn}.s3.${AWS::Region}.amazonaws.com/icloud/cfn-nested/corentsu/policies-ciclos.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName

  PoliciesPdoohd:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://${BucketCfn}.s3.${AWS::Region}.amazonaws.com/icloud/cfn-nested/corentsu/policies-pdoohd.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName

  PoliciesRdgcap:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://${BucketCfn}.s3.${AWS::Region}.amazonaws.com/icloud/cfn-nested/corentsu/policies-rdgcap.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName

  PoliciesSoport:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://${BucketCfn}.s3.${AWS::Region}.amazonaws.com/icloud/cfn-nested/corentsu/policies-soport.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName

# https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/roles-corentsu.yaml