AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Nested Stack for IAM SA.

Parameters:
  BucketName:
    Type: String
    Description: Nombre del bucket de S3

Resources:
  RolesCorentsu:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://${{ secrets.BUCKET_CFN }}.s3.${AWS::AccountId}.amazonaws.com/icloud/cfn-nested/corentsu/roles-corentsu.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName

  PoliciesCiclos:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://${{ secrets.BUCKET_CFN }}.s3.${AWS::AccountId}.amazonaws.com/icloud/cfn-nested/corentsu/policies-ciclos.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName

  PoliciesPdoohd:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://${{ secrets.BUCKET_CFN }}.s3.${AWS::AccountId}.amazonaws.com/icloud/cfn-nested/corentsu/policies-pdoohd.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName

  PoliciesRdgcap:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://${{ secrets.BUCKET_CFN }}.s3.${AWS::AccountId}.amazonaws.com/icloud/cfn-nested/corentsu/policies-rdgcap.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName

  PoliciesSoport:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://${{ secrets.BUCKET_CFN }}.s3.${AWS::AccountId}.amazonaws.com/icloud/cfn-nested/corentsu/policies-soport.yaml'
      Parameters:
        BucketNameParam: !Ref BucketName