AWSTemplateFormatVersion: '2010-09-09'
Description: Nested Stack que incluye roles, políticas de IAM para Redes Transversales y Soporte

Resources:
  RolesCorentsu:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/roles-corentsu.yaml'

  PoliciesCiclos:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-ciclos.yaml'

  PoliciesPdoohd:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-pdoohd.yaml'

  PoliciesRdgcap:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-rdgcap.yaml'

  PoliciesSoport:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-soport.yaml'