AWSTemplateFormatVersion: '2010-09-09'
Description: Definition of IAM policies

Resources:
  SNSInlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SNS-InlinePolicy"
      Roles:
        - !ImportValue RolCorentsuSoportName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sns:Publish"
            Resource:
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:TOPIC_NAME"

  SQSInlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SQS-InlinePolicy"
      Roles:
        - !ImportValue RolCorentsuSoportName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sqs:ChangeMessageVisibility"
              - "sqs:GetQueueAttributes"
              - "sqs:ReceiveMessage"
              - "sqs:SendMessage"
              - "sqs:GetQueueUrl"
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:QUEUE_NAME"

  S3InlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "S3-InlinePolicy"
      Roles:
        - !ImportValue RolCorentsuSoportName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
            Resource:
              - !Sub "arn:aws:s3:::${BucketNameParam}/soport/*"