AWSTemplateFormatVersion: '2010-09-09'
Description: Definition of IAM policies

Resources:
  SNSInlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SNS-InlinePolicy"
      Roles:
        - !ImportValue RolCorentsuPdoohdName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sns:Publish"
            Resource:
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:topic-pdoohd-pudom-agencies"

  SQSInlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SQS-InlinePolicy"
      Roles:
        - !ImportValue RolCorentsuPdoohdName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sqs:ChangeMessageVisibility"
              - "sqs:GetQueueAttributes"
              - "sqs:ReceiveMessage"
              - "sqs:SendMessage"
              - "sqs:GetQueueUrl"
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:queue-pdoohd-pudom-agencies-notify-01"