AWSTemplateFormatVersion: '2010-09-09'
Description: Definition of IAM policies

Parameters:
  BucketNameParam:
    Type: String
    Description: Nombre del bucket de S3 pasado desde el stack principal

Resources:
  SNSInlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SNS-InlinePolicy"
      Roles:
        - !ImportValue RolCorentsuCiclosName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sns:Publish"
            Resource:
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:topic-ciclos-oscor-orders"
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:topic-ciclos-optra-events"

  SQSInlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SQS-InlinePolicy"
      Roles:
        - !ImportValue RolCorentsuCiclosName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sqs:ChangeMessageVisibility"
              - "sqs:GetQueueAttributes"
              - "sqs:ReceiveMessage"
              - "sqs:SendMessage"
              - "sqs:GetQueueUrl"
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:queue-ciclos-oscor-orders-injected-01"
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:queue-ciclos-oscor-orders-updated-01"
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:queue-ciclos-optra-events-created-01"
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:queue-ciclos-optra-events-inyected-01"

  S3InlinePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "S3-InlinePolicy"
      Roles:
        - !ImportValue RolCorentsuCiclosName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
            Resource:
              - !Sub "arn:aws:s3:::${BucketNameParam}/ciclos/*"