AWSTemplateFormatVersion: '2010-09-09'
Description: Definición de políticas de IAM

Resources:
  SnsCorentsuPdoohd:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SnsCorentsuPdoohd"
      Roles:
        - !ImportValue RolCorentsuPdoohdName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sns:Publish"
            Resource:
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:topic-pdoohd-pudom-agencies"

  SqsCorentsuPdoohd:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SqsCorentsuPdoohd"
      Roles:
        - !ImportValue RolCorentsuPdoohdName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sqs:ChangeMessageVisibility"
              - "sqs:GetQueueAttributes"
              - "sqs:ReceiveMessage"
              - "sqs:SendMessage"
              - "sqs:GetQueueUrl"
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:queue-pdoohd-pudom-agencies-notify-01"