AWSTemplateFormatVersion: '2010-09-09'
Description: Definición de políticas de IAM

Resources:
  SNS-Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SNS-Policy"
      Roles:
        - !ImportValue RolCorentsuRdgcapName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sns:Publish"
            Resource:
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:TOPIC_NAME"

  SQS-Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "SQS-Policy"
      Roles:
        - !ImportValue RolCorentsuRdgcapName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sqs:ChangeMessageVisibility"
              - "sqs:GetQueueAttributes"
              - "sqs:ReceiveMessage"
              - "sqs:SendMessage"
              - "sqs:GetQueueUrl"
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:QUEUE_NAME"